version: '3.8'

services:
  food-donation:
    build: ./services/food-donation
    ports:
      - "4001:4001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/zerowaste
    depends_on:
      - mongo

  pickup:
    build: ./services/pickup
    ports:
      - "4002:4002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/zerowaste
    depends_on:
      - mongo

  review:
    build: ./services/review
    ports:
      - "4003:4003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/zerowaste
    depends_on:
      - mongo

  user:
    build: ./services/user
    ports:
      - "4004:4004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/zerowaste
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
